### ISSUE TITLE
Nodes in edge list missing from node label file

### ISSUE THREAD

**Issue by LucaCappelletti94** [sanyabt/np-kg#4]
Hello,

I was trying to create a visualization of the graph that also included the node types, but I see that a significant amount of nodes appear in [the edge list](https://zenodo.org/record/6814508/files/PheKnowLator_machine_read_merged_instance_based_OWLNETS_v1.0.nt?download=1) but is missing from the [node label file](https://zenodo.org/record/6814508/files/nodeLabels_v1.0.pickle). A small subset is:

- '<https://www.ncbi.nlm.nih.gov/snp/rs545999438>',
- '<https://www.ncbi.nlm.nih.gov/snp/rs148278350>',
- '<https://uswest.ensembl.org/Homo_sapiens/Transcript/Summary?t=ENST00000413234>',
- '<http://purl.obolibrary.org/obo/PR_P30486>',
- '<http://purl.obolibrary.org/obo/OAE_0002724>',
- '<https://uswest.ensembl.org/Homo_sapiens/Transcript/Summary?t=ENST00000651547>',
- '<http://purl.obolibrary.org/obo/CHEBI_96590>',
- '<http://purl.obolibrary.org/obo/PR_O94979>',
- '<https://reactome.org/content/detail/R-HSA-1793217>',
- '<http://purl.obolibrary.org/obo/PR_000032635>'

Should I just ignore the node types?

**Comment by sanyabt** [comment]
Hi, thanks for the information! Let me figure out why they're missing. I will update the node labels file with the missing labels and let you know once done.

**Comment by sanyabt** [comment]
Hi @LucaCappelletti94, thank you so much for opening the issue. There were 4457 missing labels in the node labels file. These have been fixed now and updated in v1.0.1 which can be downloaded [here](https://zenodo.org/record/7011488/files/nodeLabels_v1.0.1.pickle?download=1). Number of nodes is equal to 745,512. I could not find labels for 9 nodes and set the label = 'NaN' for these. Thanks again!

**Comment by LucaCappelletti94** [comment]
Perfect! May I ask why you use `pickle` in this case? These are just TSV objects, not complex Python classes. Why use a more complex format than the bare minimum?

Could you possibly upòpad the gzipped TSV version of the node-label file as well? It would let me skip a preprocessing step after downloading the data, making the graph loading process faster. [Moreover, pickle is a severe security risk, and several people would refuse to use it altogether, avoiding using these datasets.](https://medium.com/ochrona/python-pickle-is-notoriously-insecure-d6651f1974c9)

**Comment by LucaCappelletti94** [comment]
One more thing: I see that the node labels or Entity Types are node names, not node types. Is this correct?

**Comment by sanyabt** [comment]
Yes, they are node names and not node types. The graph does not include node types yet. 

I will upload the compressed TSV version here - [nodeLabels_v1.0.1_compressed.tsv.gz](https://github.com/sanyabt/np-kg/files/9395347/nodeLabels_v1.0.1_compressed.tsv.gz). I admit I use pickle more from habit than any other reason. You are correct though, it is more complex than needed. Thanks!
