### ISSUE TITLE
Extremely low number of edges compared to number of nodes

### ISSUE THREAD

**Issue by LucaCappelletti94** [sanyabt/np-kg#6]
I have loaded the [edge list directly from Zenodo](https://zenodo.org/record/6814508/files/PheKnowLator_machine_read_merged_instance_based_OWLNETS_v1.0.nt), skipping rows with NaNs, and we get that there are more nodes than edges, specifically: `21711446` and `21711146`. Is this correct? Am I doing something wrong?

With such low density, I cannot execute a surprisingly large amount of library features.

**Comment by sanyabt** [comment]
I was just debugging this and realized the edge list on Zenodo has far too many duplicates and number of nodes is also incorrect. Did not realize it as I have mostly been working with the pickle files. I will fix this and upload the new version - please wait to execute your library. I will comment on the issues once the new version is uploaded. Thanks!!

**Comment by LucaCappelletti94** [comment]
Ok, please upload the files using `gzip` compression for the new versions. I have a slow internet connection, so a smaller file would significantly speed up my iterations.

**Comment by sanyabt** [comment]
Hi @LucaCappelletti94, I updated both the TSV and node labels files and uploaded them [here](https://doi.org/10.5281/zenodo.7011488). There is also a [gzip compressed file for the edges in TSV](https://zenodo.org/record/7011488/files/NP-KG_merged_compressed.tsv.gz?download=1). I changed the format to include tab separated triples in the TSV file and removed all NaNs from the edge list so hopefully it is easier to process now. Number of nodes = 745,512 and number of edges = 7,249,578.

Thank you so much for pointing out the errors! Please let me know if you still have issues. Thanks!
