### ISSUE TITLE
Get TSV data file

### ISSUE THREAD

**Issue by YojanaGadiya** [sanyabt/np-kg#8]
Dear authors,

I have been looking into the data files deposited on Zenodo but they seem to be TASV files generated from RDF. Would it be possible for you to provide the TSV file in the following format: source curie, relation, target curie

Thank You.

**Comment by sanyabt** [comment]
Hi, thank you for your interest in NP-KG! Just to be clear, you would like the KG triples available as TSV file with source curie, relation, target curie without the RDF formatting? I can convert it for you if you can tell me which file you are trying to access from Zenodo?

**Comment by YojanaGadiya** [comment]
Hey! Yes, that's right I want the KG triple in the above format. The file I am trying to access is called NP-KG Merged TSV format.

Thank You.

**Comment by sanyabt** [comment]
Okay, no problem! I'll create the file in the format and ping you once done - should be by end of today. Thanks!

**Comment by sanyabt** [comment]
Hi @YojanaGadiya, sorry for the delay! I was able to extract all the CURIEs from the merged NP-KG file and store as source_curie, relation, target_curie. The merged KG triples file with CURIEs is available [here](https://drive.google.com/file/d/17aREyYb91luF_c4beBoJAcCdVxp-zpyT/view?usp=sharing). I also converted the TSV node labels file to CURIEs. You can download the node labels file [here](https://drive.google.com/file/d/1V8ulADjzOzeddlUOEt4gA4gczuDqlaC2/view?usp=sharing).

I am not sure about your use case but there are some instances where the CURIE prefixes were not OBO-based (http://purl.obolibrary.org/obo/) and the nodes and relations will need to be resolved differently, if you do need to resolve them. A couple cases where this might happen -

1. Custom concepts for natural products with prefix "http://napdi.org/napdi_srs_imports"
2. RDFS and RDF relations (e.g., rdfs:subClassOf and rdf:type)

For all other cases, I followed the [bioregistry](https://bioregistry.io/) CURIEs and prefix resolvers. Please let me know if this is what you were looking for and if I can help in any other way.

**Comment by YojanaGadiya** [comment]
@sanyabt it is almost like the file format I need. Could it be possible for you to resolve the relation curies to relation names since you already have the code base for this? Thank you and sorry for the trouble.

**Comment by sanyabt** [comment]
Hi @YojanaGadiya, no problem! Here is the file with CURIEs and relation labels - [link to file](https://drive.google.com/file/d/1sglc4h04OT54EdWEClAhPv246CEAbMpM/view?usp=sharing). In case you need the generation process, the Jupyter notebook I used is located [here](https://github.com/sanyabt/np-kg/blob/main/util-notebooks/NPKG-generate-tsv.ipynb). Some of the UBERON and ENVO ontology relation labels are still prefixed ("uberon:", "envo:") but I hope this will not be an issue. Thanks!

**Comment by YojanaGadiya** [comment]
@sanyabt thank you so much. Apologies for my late reply.
